CREATE TABLE IF NOT EXISTS schema_migrations(version INTEGER PRIMARY KEY, applied_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO schema_migrations(version) VALUES (1);
CREATE TABLE IF NOT EXISTS files(id INTEGER PRIMARY KEY, path TEXT NOT NULL UNIQUE, signature TEXT NOT NULL, confidence INTEGER NOT NULL, sha256 TEXT NOT NULL, size INTEGER NOT NULL, indexed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS fields(id INTEGER PRIMARY KEY, file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE, kind TEXT NOT NULL, offset INTEGER NOT NULL, size INTEGER NOT NULL, value TEXT);
CREATE TABLE IF NOT EXISTS strings(id INTEGER PRIMARY KEY, file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE, offset INTEGER NOT NULL, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS references_(id INTEGER PRIMARY KEY, file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE, offset INTEGER NOT NULL, target_hash TEXT, target_offset INTEGER, raw BLOB);
CREATE TABLE IF NOT EXISTS warnings(id INTEGER PRIMARY KEY, file_id INTEGER NOT NULL REFERENCES files(id) ON DELETE CASCADE, message TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_fields_file ON fields(file_id); CREATE INDEX IF NOT EXISTS idx_strings_value ON strings(value); CREATE INDEX IF NOT EXISTS idx_files_hash ON files(sha256);
